# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e766b44fd62cd22a3527eae01dad5bfc7a5809adf5c5a81c8d31a64474add45e3bc87d64d9227a6670a546341e4966a6ac5f40fb3f7e507138e95ce743dc9ab

test:
  secret_key_base: 16d067ade919ac283e982476475f31be9b36e6517a39e6505f7d2cb0c91a0db41813613b37b063999bdb9d8c3218c342e84ff744f5d1afcc51596d31d1f2a823

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
